export const FETCH_SEARCH = "FETCH_SEARCH";
export const IS_SEARCHING = "IS_SEARCHING";
export const SET_QUERY = "SET_QUERY";
export const SET_FAVOURITE = "SET_FAVOURITE";
export const LOAD_LOCAL_FAVOURITES = "LOAD_LOCAL_FAVOURITES";
export const SET_VEGETARIAN = "SET_VEGETARIAN";
